In [3]:

# Using Whelley et al., 2015  paper that calculated VEI Level eruption for 750 volcanoes in southeast Asia we start estimating Eruption source paramerters from VEI and probablistic volume estimates. 

# first we load Whelley 2015 Volcano Database later will be use to filter Volcanish Ash Advisory reports from Tokyo Volcanic Ash Advisory Center in realtime (computer need internet connection to parse VAA reports)

import vei 

data_loader=vei.LOADDATA()


whelley_data=data_loader.whelley_2015(as_geodataframe=True)

In [4]:
import vep_vaa_text
from vep_vaa_text import VEP_TVAAC_VAAText
#url = "https://www.data.jma.go.jp/svd/vaac/data/Archives/2020_vaac_list.html"
scraper = VEP_TVAAC_VAAText()
scraper.fetch_webpage()
tables = scraper.extract_all_tables()
tables
# Perform a search Note: for realtime operation set all parameters to None to retrive the latest report VAA report
search_results = scraper.search(query=None, date_time=None, advisory_number='2025')  # Replace with your query string, set all parameters to None to retrive latest report dates: Note takes longer processing time
downloaded_VAA_report, latest_VAA_report , latest_date_data=scraper.download_vaa_text(output_dir="./TVAAC_test", filtered_results=search_results, csv=True, gdf=whelley_data, get_latest_date_data_option=True)

downloaded_VAA_report.head(5)

2025-02-16 17:15:56,403 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,403 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,403 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,403 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,403 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,419 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,420 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,420 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,421 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,421 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,423 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,424 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,424 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,425 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,426 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,427 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,427 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,428 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,429 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,430 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,431 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,431 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,433 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,433 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,434 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,436 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,437 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,437 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,437 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,437 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,437 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,437 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,437 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,437 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,437 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,437 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,437 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,437 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,437 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,437 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,437 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,437 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,437 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,437 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,451 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,452 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,453 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,453 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,453 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,453 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,453 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,453 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,453 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,453 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,460 - INFO - Using cached elevation for (14.0, 121.0)
2025-02-16 17:15:56,460 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,460 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,460 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,460 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,460 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,460 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,460 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,460 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,460 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,468 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,469 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,470 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,471 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)
2025-02-16 17:15:56,471 - INFO - Using cached elevation for (10.416666666666666, 123.13333333333334)

CSV file created: ./TVAAC_test\vaa_texts.csv

,DTG,VAAC,VOLCANO,VOLCANO CODE,PSN,AREA,SUMMIT ELEV,ADVISORY NR,INFO SOURCE,AVIATION COLOUR CODE,...,RMK,NXT ADVISORY,Latitude,Longitude,ADVISORY_YEAR,REPORT_NUMBER,DTG_DATETIME,height_asl_meter,ground_elevation,height_agl
1,20250215/1552Z,TOKYO,TAAL,273070,N1400 E12100,PHILIPPINES,311M,2025/2,HIMAWARI-9 PHIVOLCS,NIL,...,WE WILL ISSUE FURTHER ADVISORY IF VA IS DETECT...,NO FURTHER ADVISORIES=,14.000000,121.000000,2025,2,2025-02-15 15:52:00,NaN,130.0,NaN
2,20250215/0735Z,TOKYO,KANLAON,272020,N1025 E12308,PHILIPPINES,2435M,2025/69,HIMAWARI-9 PHIVOLCS,NIL,...,WE WILL ISSUE FURTHER ADVISORY IF VA IS DETECT...,NO FURTHER ADVISORIES=,10.416667,123.133333,2025,69,2025-02-15 07:35:00,NaN,2261.0,NaN
3,20250215/0702Z,TOKYO,KANLAON,272020,N1025 E12308,PHILIPPINES,2435M,2025/68,HIMAWARI-9 PHIVOLCS,NIL,...,WE WILL ISSUE FURTHER ADVISORY IF VA IS DETECT...,NO FURTHER ADVISORIES=,10.416667,123.133333,2025,68,2025-02-15 07:02:00,NaN,2261.0,NaN
32,20250206/0746Z,TOKYO,KANLAON,272020,N1025 E12308,PHILIPPINES,2435M,2025/67,HIMAWARI-9 PHIVOLCS,NIL,...,WE WILL ISSUE FURTHER ADVISORY IF VA IS DETECT...,NO FURTHER ADVISORIES=,10.416667,123.133333,2025,67,2025-02-06 07:46:00,NaN,2261.0,NaN
43,20250203/0020Z,TOKYO,KANLAON,272020,N1025 E12308,PHILIPPINES,2435M,2025/66,HIMAWARI-9 PHIVOLCS,NIL,...,WE WILL ISSUE FURTHER ADVISORY IF VA IS DETECT...,NO FURTHER ADVISORIES=,10.416667,123.133333,2025,66,2025-02-03 00:20:00,NaN,2261.0,NaN

In [ ]:
latest_date_data

In [5]:
from vep_vaa_text import MAGMA_VONA_PARSER

parser = MAGMA_VONA_PARSER("All Volcanoes", BASE_FOLDER='Magma_Test')

# Scrape all reports and extract URLs
parser.scrape_all_reports(max_pages=3)

# Extract detailed VONA reports from scraped URLs
parser.extract_vona_reports()

Scraping up to 3 pages for All Volcanoes...

🔄 Scraping Pages: 100%|██████████| 3/3 [00:13<00:00,  4.38s/page]

Scraping completed. Data saved at Magma_Test\vona_reports_sorted.csv
Extracting details from 45 reports...

📝 Extracting Reports:   0%|          | 0/45 [00:00<?, ?report/s]2025-02-16 17:16:11,071 - WARNING - Connection pool is full, discarding connection: magma.esdm.go.id. Connection pool size: 10
2025-02-16 17:16:11,085 - WARNING - Connection pool is full, discarding connection: magma.esdm.go.id. Connection pool size: 10
2025-02-16 17:16:11,120 - WARNING - Connection pool is full, discarding connection: magma.esdm.go.id. Connection pool size: 10
2025-02-16 17:16:11,152 - WARNING - Connection pool is full, discarding connection: magma.esdm.go.id. Connection pool size: 10
2025-02-16 17:16:11,169 - WARNING - Connection pool is full, discarding connection: magma.esdm.go.id. Connection pool size: 10
2025-02-16 17:16:11,245 - WARNING - Connection pool is full, discarding connection: magma.esdm.go.id. Connection pool size: 10
📝 Extracting Reports: 100%|██████████| 45/45 [00:01<00:00, 27.78report/s]

💾 Saving extracted reports...

📁 Saving Reports:  44%|████▍     | 20/45 [00:00<00:00, 194.98file/s]

✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250217-0053Z_Ibu_(268030).txt
✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250217-0056Z_Semeru_(263300).txt
✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250217-0028Z_Ibu_(268030).txt
✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250216-2329Z_Semeru_(263300).txt
✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250216-2305Z_Semeru_(263300).txt
✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250216-2158Z_Lewotobi_Laki-laki_(264180).txt
✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250216-1825Z_Semeru_(263300).txt
✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250216-1548Z_Semeru_(263300).txt
✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250216-1531Z_Semeru_(263300).txt
✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250216-1407Z_Semeru_(263300).txt
✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250216-1302Z_Semeru_(263300).txt
✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250216-0921Z_Semeru_(263300).txt
✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250216-0907Z_Semeru_(263300).txt
✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250216-0852Z_Semeru_(263300).txt
✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250216-0840Z_Ibu_(268030).txt
✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250216-0842Z_Semeru_(263300).txt
✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250216-0841Z_Semeru_(263300).txt
✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250216-0819Z_Ibu_(268030).txt
✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250216-0816Z_Semeru_(263300).txt
✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250216-0724Z_Semeru_(263300).txt
✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250216-0539Z_Semeru_(263300).txt
✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250216-0523Z_Semeru_(263300).txt
✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250216-0515Z_Semeru_(263300).txt
✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250216-0440Z_Semeru_(263300).txt
✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250216-0353Z_Semeru_(263300).txt
✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250216-0338Z_Semeru_(263300).txt
✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250216-0312Z_Semeru_(263300).txt
✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250216-0224Z_Semeru_(263300).txt
✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250216-0032Z_Ibu_(268030).txt
✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250215-2350Z_Ibu_(268030).txt
✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250215-2234Z_Semeru_(263300).txt
✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250215-2000Z_Semeru_(263300).txt
✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250215-1940Z_Semeru_(263300).txt
✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250215-1541Z_Semeru_(263300).txt
✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250215-1433Z_Semeru_(263300).txt

📁 Saving Reports: 100%|██████████| 45/45 [00:00<00:00, 197.54file/s]

✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250215-1417Z_Ibu_(268030).txt
✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250215-1401Z_Semeru_(263300).txt
✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250215-1322Z_Ibu_(268030).txt
✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250215-1304Z_Ibu_(268030).txt
✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250215-1217Z_Ibu_(268030).txt
✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250215-1137Z_Semeru_(263300).txt
✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250215-1055Z_Ibu_(268030).txt
✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250215-0938Z_Semeru_(263300).txt
✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250215-0758Z_Semeru_(263300).txt
✅ Data saved: Magma_Test\detailed_reports\VONA_Report_20250215-0532Z_Semeru_(263300).txt
Detailed reports extracted successfully!

,Source_URL,Issued,Volcano,Current Aviation Colour Code,Previous Aviation Colour Code,Source,Notice Number,Volcano Location,Area,Summit Elevation,Volcanic Activity Summary,Volcanic Cloud Height,Other Volcanic Cloud Information,Remarks,Contacts,Next Notice
0,https://magma.esdm.go.id/v1/vona/14967?signatu...,20250217/0053Z,Ibu (268030),ORANGE,orange,Ibu Volcano Observatory,2025IBU327,N 01 deg 29 min 17 sec E 127 deg 37 min 48 sec,"North Maluku, Indonesia",4240 FT (1325 M),Eruption with volcanic ash cloud at 0053 UTC (...,Best estimate of ash-cloud top is around 6800 ...,Ash cloud moving to northwest. Volcanic ash is...,Eruption recorded on seismogram with maximum a...,Center for Volcanology and Geological Hazard M...,A new VONA will be issued if conditions change...
1,https://magma.esdm.go.id/v1/vona/14966?signatu...,20250217/0056Z,Semeru (263300),ORANGE,orange,Semeru Volcano Observatory,2025SMR829,S 08 deg 06 min 29 sec E 112 deg 55 min 12 sec,"East java, Indonesia",11763 FT (3676 M),Eruption at 0056 UTC (0756 local).,Ash-cloud is not observed.,Ash-cloud is not observed.,Eruption recorded on seismogram with maximum a...,Center for Volcanology and Geological Hazard M...,A new VONA will be issued if conditions change...
2,https://magma.esdm.go.id/v1/vona/14965?signatu...,20250217/0028Z,Ibu (268030),ORANGE,orange,Ibu Volcano Observatory,2025IBU326,N 01 deg 29 min 17 sec E 127 deg 37 min 48 sec,"North Maluku, Indonesia",4240 FT (1325 M),Eruption with volcanic ash cloud at 0028 UTC (...,Best estimate of ash-cloud top is around 6480 ...,Ash cloud moving to northwest. Volcanic ash is...,Eruption recorded on seismogram with maximum a...,Center for Volcanology and Geological Hazard M...,A new VONA will be issued if conditions change...
3,https://magma.esdm.go.id/v1/vona/14964?signatu...,20250216/2329Z,Semeru (263300),ORANGE,orange,Semeru Volcano Observatory,2025SMR828,S 08 deg 06 min 29 sec E 112 deg 55 min 12 sec,"East java, Indonesia",11763 FT (3676 M),Eruption at 2329 UTC (0629 local).,Ash-cloud is not observed.,Ash-cloud is not observed.,Eruption recorded on seismogram with maximum a...,Center for Volcanology and Geological Hazard M...,A new VONA will be issued if conditions change...
4,https://magma.esdm.go.id/v1/vona/14963?signatu...,20250216/2305Z,Semeru (263300),ORANGE,orange,Semeru Volcano Observatory,2025SMR827,S 08 deg 06 min 29 sec E 112 deg 55 min 12 sec,"East java, Indonesia",11763 FT (3676 M),Eruption at 2305 UTC (0605 local).,Ash-cloud is not observed.,Ash-cloud is not observed.,Eruption recorded on seismogram with maximum a...,Center for Volcanology and Geological Hazard M...,A new VONA will be issued if conditions change...
5,https://magma.esdm.go.id/v1/vona/14961?signatu...,20250216/2158Z,Lewotobi Laki-laki (264180),ORANGE,orange,Lewotobi Laki-laki Volcano Observatory,2025LWK044,S 08 deg 32 min 20 sec E 122 deg 46 min 06 sec,"East Nusa Tenggara, Indonesia",5069 FT (1584 M),Eruption with volcanic ash cloud at 2158 UTC (...,Best estimate of ash-cloud top is around 7949 ...,Ash cloud moving to northeast. Volcanic ash is...,Eruption recorded on seismogram with maximum a...,Center for Volcanology and Geological Hazard M...,A new VONA will be issued if conditions change...
6,https://magma.esdm.go.id/v1/vona/14960?signatu...,20250216/1825Z,Semeru (263300),ORANGE,orange,Semeru Volcano Observatory,2025SMR826,S 08 deg 06 min 29 sec E 112 deg 55 min 12 sec,"East java, Indonesia",11763 FT (3676 M),Eruption at 1825 UTC (0125 local).,Ash-cloud is not observed.,Ash-cloud is not observed.,Eruption recorded on seismogram with maximum a...,Center for Volcanology and Geological Hazard M...,A new VONA will be issued if conditions change...
7,https://magma.esdm.go.id/v1/vona/14959?signatu...,20250216/1548Z,Semeru (263300),ORANGE,orange,Semeru Volcano Observatory,2025SMR825,S 08 deg 06 min 29 sec E 112 deg 55 min 12 sec,"East java, Indonesia",11763 FT (3676 M),Eruption at 1548 UTC (2248 local).,Ash-cloud is not observed.,Ash-cloud is not observed.,Eruption recorded on seismogram with maximum a...,Center for Volcanology and Geological Hazard M...,A new VONA will be issued if conditions change...
8,https://magma.esdm.go.id/v1/vona/14958?signatu...,20250216/1531Z,Semeru (263300),ORANGE,orange,Semeru Volcano Observatory,2025SMR824,S 08 deg 06 min 29 sec E 112 deg 55 min 12 sec,"East java, Indonesia",11763 FT (3676 M),Eruption at 1531 UTC (2231 local).,Ash-cloud is not observed.,Ash-cloud is not observed.,Eruption recorded on seismogram with maximum a...,Center for Volcanology and Geological Hazard M...,A new VONA will be issued if conditions change...
9,https://magma.esdm.go.id/v1/vona/14957?signatu...,20250216/1407Z,Semeru (263300),ORANGE,orange,Semeru Volcano Observatory,2025SMR823,S 08 deg 06 min 29 sec E 112 deg 55 min 12 sec,"East java, Indonesia",11763 FT (3676 M),Eruption at 1407 UTC (2107 local).,Ash-cloud is not observed.,Ash-cloud is not observed.,Eruption recorded on seismogram with maximum a...,Center for Volcanology and Geological Hazard M...,A new VONA will be issued if conditions change...
10,https://magma.esdm.go.id/v1/vona/14956?signatu...,20250216/1302Z,Semeru (263300),ORANGE,orange,Semeru Volcano Observatory,2025SMR822,S 08 deg 06 min 29 sec E 112 deg 55 min 12 sec,"East java, Indonesia",11763 FT (3676 M),Eruption at 1302 UTC (2002 local).,Ash-cloud is not observed.,Ash-cloud is not observed.,Eruption recorded on seismogram with maximum a...,Center for Volcanology and Geological Hazard M...,A new VONA will be issued if conditions change...
11,https://magma.esdm.go.id/v1/vona/14955?signatu...,20250216/0921Z,Semeru (263300),ORANGE,orange,Semeru Volcano Observatory,2025SMR821,S 08 deg 06 min 29 sec E 112 deg 55 min 12 sec,"East java, Indonesia",11763 FT (3676 M),Eruption at 0921 UTC (1621 local).,Ash-cloud is not observed.,Ash-cloud is not observed.,Eruption recorded on seismogram with maximum a...,Center for Volcanology and Geological Hazard M...,A new VONA will be issued if conditions change...
12,https://magma.esdm.go.id/v1/vona/14954?signatu...,20250216/0907Z,Semeru (263300),ORANGE,orange,Semeru Volcano Observatory,2025SMR820,S 08 deg 06 min 29 sec E 112 deg 55 min 12 sec,"East java, Indonesia",11763 FT (3676 M),Eruption at 0907 UTC (1607 local).,Ash-cloud is not observed.,Ash-cloud is not observed.,Eruption recorded on seismogram with maximum a...,Center for Volcanology and Geological Hazard M...,A new VONA will be issued if conditions change...
13,https://magma.esdm.go.id/v1/vona/14953?signatu...,20250216/0852Z,Semeru (263300),ORANGE,orange,Semeru Volcano Observatory,2025SMR819,S 08 deg 06 min 29 sec E 112 deg 55 min 12 sec,"East java, Indonesia",11763 FT (3676 M),Eruption at 0852 UTC (1552 local).,Ash-cloud is not observed.,Ash-cloud is not observed.,Eruption recorded on seismogram with maximum a...,Center for Volcanology and Geological Hazard M...,A new VONA will be issued if conditions change...
14,https://magma.esdm.go.id/v1/vona/14952?signatu...,20250216/0840Z,Ibu (268030),ORANGE,orange,Ibu Volcano Observatory,2025IBU325,N 01 deg 29 min 17 sec E 127 deg 37 min 48 sec,"North Maluku, Indonesia",4240 FT (1325 M),Eruption with volcanic ash cloud at 0840 UTC (...,Best estimate of ash-cloud top is around 8080 ...,Ash cloud moving to northwest. Volcanic ash is...,Eruption recorded on seismogram with maximum a...,Center for Volcanology and Geological Hazard M...,A new VONA will be issued if conditions change...
15,https://magma.esdm.go.id/v1/vona/14951?signatu...,20250216/0842Z,Semeru (263300),ORANGE,orange,Semeru Volcano Observatory,2025SMR818,S 08 deg 06 min 29 sec E 112 deg 55 min 12 sec,"East java, Indonesia",11763 FT (3676 M),Eruption at 0842 UTC (1542 local).,Ash-cloud is not observed.,Ash-cloud is not observed.,Eruption recorded on seismogram with maximum a...,Center for Volcanology and Geological Hazard M...,A new VONA will be issued if conditions change...
16,https://magma.esdm.go.id/v1/vona/14950?signatu...,20250216/0841Z,Semeru (263300),ORANGE,orange,Semeru Volcano Observatory,2025SMR817,S 08 deg 06 min 29 sec E 112 deg 55 min 12 sec,"East java, Indonesia",11763 FT (3676 M),Eruption at 0841 UTC (1541 local).,Ash-cloud is not observed.,Ash-cloud is not observed.,Eruption recorded on seismogram with maximum a...,Center for Volcanology and Geological Hazard M...,A new VONA will be issued if conditions change...
17,https://magma.esdm.go.id/v1/vona/14949?signatu...,20250216/0819Z,Ibu (268030),ORANGE,orange,Ibu Volcano Observatory,2025IBU324,N 01 deg 29 min 17 sec E 127 deg 37 min 48 sec,"North Maluku, Indonesia",4240 FT (1325 M),Eruption at 0819 UTC (1719 local).,Ash-cloud is not observed.,Ash-cloud is not observed.,Eruption recorded on seismogram with maximum a...,Center for Volcanology and Geological Hazard M...,A new VONA will be issued if conditions change...
18,https://magma.esdm.go.id/v1/vona/14948?signatu...,20250216/0816Z,Semeru (263300),ORANGE,orange,Semeru Volcano Observatory,2025SMR816,S 08 deg 06 min 29 sec E 112 deg 55 min 12 sec,"East java, Indonesia",11763 FT (3676 M),Eruption at 0816 UTC (1516 local).,Ash-cloud is not observed.,Ash-cloud is not observed.,Eruption recorded on seismogram with maximum a...,Center for Volcanology and Geological Hazard M...,A new VONA will be issued if conditions change...
19,https://magma.esdm.go.id/v1/vona/14947?signatu...,20250216/0724Z,Semeru (263300),ORANGE,orange,Semeru Volcano Observatory,2025SMR815,S 08 deg 06 min 29 sec E 112 deg 55 min 12 sec,"East java, Indonesia",11763 FT (3676 M),Eruption at 0724 UTC (1424 local).,Ash-cloud is not observed.,Ash-cloud is not observed.,Eruption recorded on seismogram with maximum a...,Center for Volcanology and Geological Hazard M...,A new VONA will be issued if conditions change...
20,https://magma.esdm.go.id/v1/vona/14946?signatu...,20250216/0539Z,Semeru (263300),ORANGE,orange,Semeru Volcano Observatory,2025SMR814,S 08 deg 06 min 29 sec E 112 deg 55 min 12 sec,"East java, Indonesia",11763 FT (3676 M),Eruption at 0539 UTC (1239 local).,Ash-cloud is not observed.,Ash-cloud is not observed.,Eruption recorded on seismogram with maximum a...,Center for Volcanology and Geological Hazard M...,A new VONA will be issued if conditions change...
21,https://magma.esdm.go.id/v1/vona/14945?signatu...,20250216/0523Z,Semeru (263300),ORANGE,orange,Semeru Volcano Observatory,2025SMR813,S 08 deg 06 min 29 sec E 112 deg 55 min 12 sec,"East java, Indonesia",11763 FT (3676 M),Eruption at 0523 UTC (1223 local).,Ash-cloud is not observed.,Ash-cloud is not observed.,Eruption recorded on seismogram with maximum a...,Center for Volcanology and Geological Hazard M...,A new VONA will be issued if conditions change...
22,https://magma.esdm.go.id/v1/vona/14944?signatu...,20250216/0515Z,Semeru (263300),ORANGE,orange,Semeru Volcano Observatory,2025SMR812,S 08 deg 06 min 29 sec E 112 deg 55 min 12 sec,"East java, Indonesia",11763 FT (3676 M),Eruption at 0515 UTC (1215 local).,Ash-cloud is not observed.,Ash-cloud is not observed.,Eruption recorded on seismogram with maximum a...,Center for Volcanology and Geological Hazard M...,A new VONA will be issued if conditions change...
23,https://magma.esdm.go.id/v1/vona/14943?signatu...,20250216/0440Z,Semeru (263300),ORANGE,orange,Semeru Volcano Observatory,2025SMR811,S 08 deg 06 min 29 sec E 112 deg 55 min 12 sec,"East java, Indonesia",11763 FT (3676 M),Eruption at 0440 UTC (1140 local).,Ash-cloud is not observed.,Ash-cloud is not observed.,Eruption recorded on seismogram with maximum a...,Center for Volcanology and Geological Hazard M...,A new VONA will be issued if conditions change...
24,https://magma.esdm.go.id/v1/vona/14942?signatu...,20250216/0353Z,Semeru (263300),ORANGE,orange,Semeru Volcano Observatory,2025SMR810,S 08 deg 06 min 29 sec E 112 deg 55 min 12 sec,"East java, Indonesia",11763 FT (3676 M),Eruption at 0353 UTC (1053 local).,Ash-cloud is not observed.,Ash-cloud is not observed.,Eruption recorded on seismogram with maximum a...,Center for Volcanology and Geological Hazard M...,A new VONA will be issued if conditions change...
25,https://magma.esdm.go.id/v1/vona/14941?signatu...,20250216/0338Z,Semeru (263300),ORANGE,orange,Semeru Volcano Observatory,2025SMR809,S 08 deg 06 min 29 sec E 112 deg 55 min 12 sec,"East java, Indonesia",11763 FT (3676 M),Eruption at 0338 UTC (1038 local).,Ash-cloud is not observed.,Ash-cloud is not observed.,Eruption recorded on seismogram with maximum a...,Center for Volcanology and Geological Hazard M...,A new VONA will be issued if conditions change...
26,https://magma.esdm.go.id/v1/vona/14940?signatu...,20250216/0312Z,Semeru (263300),ORANGE,orange,Semeru Volcano Observatory,2025SMR808,S 08 deg 06 min 29 sec E 112 deg 55 min 12 sec,"East java, Indonesia",11763 FT (3676 M),Eruption at 0312 UTC (1012 local).,Ash-cloud is not observed.,Ash-cloud is not observed.,Eruption recorded on seismogram with maximum a...,Center for Volcanology and Geological Hazard M...,A new VONA will be issued if conditions change...
27,https://magma.esdm.go.id/v1/vona/14939?signatu...,20250216/0224Z,Semeru (263300),ORANGE,orange,Semeru Volcano Observatory,2025SMR807,S 08 deg 06 min 29 sec E 112 deg 55 min 12 sec,"East java, Indonesia",11763 FT (3676 M),Eruption at 0224 UTC (0924 local).,Ash-cloud is not observed.,Ash-cloud is not observed.,Eruption recorded on seismogram with maximum a...,Center for Volcanology and Geological Hazard M...,A new VONA will be issued if conditions change...
28,https://magma.esdm.go.id/v1/vona/14938?signatu...,20250216/0032Z,Ibu (268030),ORANGE,orange,Ibu Volcano Observatory,2025IBU323,N 01 deg 29 min 17 sec E 127 deg 37 min 48 sec,"North Maluku, Indonesia",4240 FT (1325 M),Eruption with volcanic ash cloud at 0032 UTC (...,Best estimate of ash-cloud top is around 6800 ...,Ash cloud moving to northwest. Volcanic ash is...,Eruption recorded on seismogram with maximum a...,Center for Volcanology and Geological Hazard M...,A new VONA will be issued if conditions change...
29,https://magma.esdm.go.id/v1/vona/14937?signatu...,20250215/2350Z,Ibu (268030),ORANGE,orange,Ibu Volcano Observatory,2025IBU322,N 01 deg 29 min 17 sec E 127 deg 37 min 48 sec,"North Maluku, Indonesia",4240 FT (1325 M),Eruption with volcanic ash cloud at 2350 UTC (...,Best estimate of ash-cloud top is around 6160 ...,Ash cloud moving to northwest. Volcanic ash is...,Eruption recorded on seismogram with maximum a...,Center for Volcanology and Geological Hazard M...,A new VONA will be issued if conditions change...
30,https://magma.esdm.go.id/v1/vona/14936?signatu...,20250215/2234Z,Semeru (263300),ORANGE,orange,Semeru Volcano Observatory,2025SMR806,S 08 deg 06 min 29 sec E 112 deg 55 min 12 sec,"East java, Indonesia",11763 FT (3676 M),Eruption with volcanic ash cloud at 2234 UTC (...,Best estimate of ash-cloud top is around 13363...,Ash cloud moving from north to northeast. Volc...,Eruption recorded on seismogram with maximum a...,Center for Volcanology and Geological Hazard M...,A new VONA will be issued if conditions change...
31,https://magma.esdm.go.id/v1/vona/14935?signatu...,20250215/2000Z,Semeru (263300),ORANGE,orange,Semeru Volcano Observatory,2025SMR805,S 08 deg 06 min 29 sec E 112 deg 55 min 12 sec,"East java, Indonesia",11763 FT (3676 M),Eruption at 2000 UTC (0300 local).,Ash-cloud is not observed.,Ash-cloud is not observed.,Eruption recorded on seismogram with maximum a...,Center for Volcanology and Geological Hazard M...,A new VONA will be issued if conditions change...
32,https://magma.esdm.go.id/v1/vona/14934?signatu...,20250215/1940Z,Semeru (263300),ORANGE,orange,Semeru Volcano Observatory,2025SMR804,S 08 deg 06 min 29 sec E 112 deg 55 min 12 sec,"East java, Indonesia",11763 FT (3676 M),Eruption with volcanic ash cloud at 1940 UTC (...,Best estimate of ash-cloud top is around 13363...,Ash cloud moving to north. Volcanic ash is obs...,Eruption recorded on seismogram with maximum a...,Center for Volcanology and Geological Hazard M...,A new VONA will be issued if conditions change...
33,https://magma.esdm.go.id/v1/vona/14933?signatu...,20250215/1541Z,Semeru (263300),ORANGE,orange,Semeru Volcano Observatory,2025SMR803,S 08 deg 06 min 29 sec E 112 deg 55 min 12 sec,"East java, Indonesia",11763 FT (3676 M),Eruption with volcanic ash cloud at 1541 UTC (...,Best estimate of ash-cloud top is around 14003...,Ash cloud moving to southeast. Volcanic ash is...,Eruption recorded on seismogram with maximum a...,Center for Volcanology and Geological Hazard M...,A new VONA will be issued if conditions change...
34,https://magma.esdm.go.id/v1/vona/14932?signatu...,20250215/1433Z,Semeru (263300),ORANGE,orange,Semeru Volcano Observatory,2025SMR802,S 08 deg 06 min 29 sec E 112 deg 55 min 12 sec,"East java, Indonesia",11763 FT (3676 M),Eruption at 1433 UTC (2133 local).,Ash-cloud is not observed.,Ash-cloud is not observed.,Eruption recorded on seismogram with maximum a...,Center for Volcanology and Geological Hazard M...,A new VONA will be issued if conditions change...
35,https://magma.esdm.go.id/v1/vona/14931?signatu...,20250215/1417Z,Ibu (268030),ORANGE,orange,Ibu Volcano Observatory,2025IBU321,N 01 deg 29 min 17 sec E 127 deg 37 min 48 sec,"North Maluku, Indonesia",4240 FT (1325 M),Eruption with volcanic ash cloud at 1417 UTC (...,Best estimate of ash-cloud top is around 6160 ...,Ash cloud moving to northwest. Volcanic ash is...,Eruption recorded on seismogram with maximum a...,Center for Volcanology and Geological Hazard M...,A new VONA will be issued if conditions change...
36,https://magma.esdm.go.id/v1/vona/14930?signatu...,20250215/1401Z,Semeru (263300),ORANGE,orange,Semeru Volcano Observatory,2025SMR801,S 08 deg 06 min 29 sec E 112 deg 55 min 12 sec,"East java, Indonesia",11763 FT (3676 M),Eruption at 1401 UTC (2101 local).,Ash-cloud is not observed.,Ash-cloud is not observed.,Eruption recorded on seismogram with maximum a...,Center for Volcanology and Geological Hazard M...,A new VONA will be issued if conditions change...
37,https://magma.esdm.go.id/v1/vona/14929?signatu...,20250215/1322Z,Ibu (268030),ORANGE,orange,Ibu Volcano Observatory,2025IBU320,N 01 deg 29 min 17 sec E 127 deg 37 min 48 sec,"North Maluku, Indonesia",4240 FT (1325 M),Eruption with volcanic ash cloud at 1322 UTC (...,Best estimate of ash-cloud top is around 8080 ...,Ash cloud moving from west to northwest. Volca...,Eruption recorded on seismogram with maximum a...,Center for Volcanology and Geological Hazard M...,A new VONA will be issued if conditions change...
38,https://magma.esdm.go.id/v1/vona/14928?signatu...,20250215/1304Z,Ibu (268030),ORANGE,orange,Ibu Volcano Observatory,2025IBU319,N 01 deg 29 min 17 sec E 127 deg 37 min 48 sec,"North Maluku, Indonesia",4240 FT (1325 M),Eruption with volcanic ash cloud at 1304 UTC (...,Best estimate of ash-cloud top is around 5520 ...,Ash cloud moving to northwest. Volcanic ash is...,Eruption recorded on seismogram with maximum a...,Center for Volcanology and Geological Hazard M...,A new VONA will be issued if conditions change...
39,https://magma.esdm.go.id/v1/vona/14927?signatu...,20250215/1217Z,Ibu (268030),ORANGE,orange,Ibu Volcano Observatory,2025IBU318,N 01 deg 29 min 17 sec E 127 deg 37 min 48 sec,"North Maluku, Indonesia",4240 FT (1325 M),Eruption with volcanic ash cloud at 1217 UTC (...,Best estimate of ash-cloud top is around 5840 ...,Ash cloud moving to northwest. Volcanic ash is...,Eruption recorded on seismogram with maximum a...,Center for Volcanology and Geological Hazard M...,A new VONA will be issued if conditions change...